### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by dannySerso63** [itsme-sdk/itsme-packages#4]
Hi Jan , your team changed the package for Golan since it was coded for the Life environment.
Is this modification also pending for the DOTNET CORE version.
I refer to the closed issue on Golan "Library is not usable on the sandbox environment"
We re writing a federation service and the call stucks. Thanks for your appreciated help danny [at] serso.be

**Comment by JanDeDobbeleer** [comment]
Hey @dannySerso63, I'm pleased to inform you that with #5 we are having this support as well for DotNet Core. Should land today.
